{{- if .Values.maxUnavailable }}
apiVersion: policy/v1
{{- else}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
   name: {{ include "http-server.fullname" . }}

spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "http-server.selectorLabels" . | nindent 6 }}
{{- end }}
